### ISSUE TITLE
How about a screenshot in your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [LoadingOfficial/GamePrinter#1]
Hi!!

You've got a GUI in your program... a rare thing in Python.  It would be great for visitors to see how it looks.  Can you add a screenshot in your Readme?  Instructions can be found in the PySimpleGUI Cookbook.

I noticed that you performs this import:
https://github.com/LoadingOfficial/GamePrinter/blob/12b8c47696c734211671c0bfdc3099e2d316ab36/gui.py#L2

Not a good idea to do this as mentioned in the PySimpleGUI documentation.  It pollutes your namespace, etc.

It's great to see you've got a GUI... I'm anxious to see how it looks.  Doesn't have to be fancy to be awesome to see
![image](https://user-images.githubusercontent.com/46163555/168252927-fe08fdca-c193-4366-8708-24156f67df3a.png)

**Comment by LoadingOfficial** [comment]
Hellow!

Thank you for creating this amazing GUI library! I couldn't have made this project without it

I will add some screenshots at the earliest convenience (later today maybe).

Also, I know that importing "all" bloats the namespace but the file is only used for some simple layout and some simple gui related functions so it's it's not like I'm doing that in "main.py" and it also makes adding stuff in the future easier!

**Keep being awesome!** 

_Sent from my AC2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PySimpleGUI** [comment]
You are **very welcome**!

Thank you for the kind words.  It's hard to describe the impact of hearing statements like yours... that PySimpleGUI enabled you to do something that you believe you wouldn't have been able to do without it.  It hits right in the heart every time ![image](https://user-images.githubusercontent.com/46163555/168290634-d2d42a74-c3cc-4d83-b3c1-2702a68d4201.png).  It fuels the project... keeps me working as hard as I can at this.

Glad you're aware of the namespace pollution problem.  Just don't post your code in a tutorial please!  I don't want to end up like tkinter with these imports being spread.  The coding conventions published in the documentation have been followed by the vast majority of users.  I rely on those to run searches across GitHub to gain an understanding of exactly what features are being used and how.  It's enabled me to make better decisions.

Keep building!  Thank you so much for the encouraging words!!

![image](https://user-images.githubusercontent.com/46163555/168291625-6f59d0df-1b6d-4f1c-947b-29a4fa64a2c6.png)

**Comment by LoadingOfficial** [comment]
Hellow again!!

> "Just don't post your code in a tutorial please"

I am bad at explaining stuff and I'm not qualified enough with the library to make a tutorial XD... I would recommend people to learn to use it though the documentation!

**+** Added a screenshot to the _README.md_ with a nice background, thanks for the tip...
Also again, thanks for inspiring me to create!

Peace

**Comment by PySimpleGUI** [comment]
> Also again, thanks for inspiring me to create!

My big discovery over the past year.....

![ItsCircular](https://user-images.githubusercontent.com/46163555/168309489-1fd22c80-576f-43c4-9ab0-59da9f131519.jpg)


YOU inspired me!
